# Generated by Django 5.1 on 2024-08-27 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_page_picture_alter_page_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='diary/picture/', verbose_name='写真'),
        ),
    ]
